In [1]:
import pandas as pd
import numpy as np


In [2]:
pd.set_option('display.max_colwidth',None)  

In [3]:
df=pd.read_excel("dataset/FINAL.xlsx")

In [4]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import re

In [5]:
nepali_stopwords = set(stopwords.words('nepali'))

In [6]:
english_stopwords = set(stopwords.words('english'))

In [7]:
def preprocess_text(text):
    # Convert to lowercase
    text = text.lower()
    # Remove specified characters
    text = re.sub('[#\\/।(),०-९<<?!,—–’‘:\u200d]', '', text)
    # Strip double quotes
    text = text.strip('"')

    # Tokenize the text
    words=word_tokenize(text)
    # Remove stop words for both Nepali and English
    filtered_words = [word for word in words if word.lower() not in nepali_stopwords and word.lower() not in english_stopwords]
    # Join the filtered words to form the processed text
    processed_text = ' '.join(filtered_words)
    return processed_text


In [8]:
df['गुनासो'] = df['गुनासो'].apply(preprocess_text)


In [9]:
from sklearn.model_selection import train_test_split

In [10]:
df['गुनासो वर्ग no']=df['गुनासो वर्ग'].map({
    'लागु पदार्थ सम्बन्धी ':0,
    'प्राकृतिक श्रोत/साधन सम्बन्धी':1,
    'अर्थिक अनियमितता तथा भ्रष्टाचार सम्बन्धी ':2,
    'कर्मचारी सम्वन्धी ':3,
    'अर्थ सबन्धी ':4,
    'सोधपुछ, सुझाव, प्रशंसा सम्बन्धी':5,
    'सूचना तथा  संचार सम्बन्धी ':6,
   'सूचना तथा  संचार सम्बन्धी':7,
    'स्वास्थ्यसँग सम्बन्धी':8,
    'वेबसाइट तथा अभिलेख व्यवस्थापन सम्बन्धी ':9,
    'शान्ति सुरक्षा सम्बन्धी ':10,
    'खानेपानी सम्बन्धी ':11,

})
df.sample(5)

गुनासो वर्ग  \
6681  वेबसाइट तथा अभिलेख व्यवस्थापन सम्बन्धी    
9406                 शान्ति सुरक्षा सम्बन्धी    
5125                सूचना तथा  संचार सम्बन्धी   
5611                    स्वास्थ्यसँग सम्बन्धी   
3432          सोधपुछ, सुझाव, प्रशंसा सम्बन्धी   

                                                                                                                                                                     गुनासो  \
6681                                                                                                                         mero voter id address different dekhauxa .....   
9406  error paying customer .i paid basis error commission twice sunrise bank ltd.\no.i.-suman tiwari.\no.i.-arbin singh chettri.\nrespectively.\non disdaining & slapped .   
5125                                    pratek maina 2- 3 din network lae kam gardaina kina hola . sarkari company lai dharashai bhanaune chalkel ho ki aru nai ke karan ho   
5611               madhumalla health post upgrade hospital soon podsible . beleoved late grandfather wish . gave area build hospital . keep one permanent physican doctor .   
3432                                                                                                                                  mero citizenship link garnu apryo app   

      गुनासो वर्ग no  
6681               9  
9406              10  
5125               7  
5611               8  
3432               5

In [11]:
df_1=df[df['गुनासो वर्ग']=='वेबसाइट तथा अभिलेख व्यवस्थापन सम्बन्धी ']
df_1.shape

(2863, 3)

In [12]:
df_2=df[df['गुनासो वर्ग']=='सोधपुछ, सुझाव, प्रशंसा सम्बन्धी'].sample(2863,replace=True)
df_2 = df_2.reset_index(drop=True)
df_2.shape

(2863, 3)

In [13]:
df_3=df[df['गुनासो वर्ग']=='कर्मचारी सम्वन्धी '].sample(2863,replace=True)
df_3 = df_3.reset_index(drop=True)
df_3.shape

(2863, 3)

In [14]:
df_4=df[df['गुनासो वर्ग']=='स्वास्थ्यसँग सम्बन्धी'].sample(2863,replace=True)
df_4 = df_4.reset_index(drop=True)
df_4.shape


(2863, 3)

In [15]:
df_5=df[df['गुनासो वर्ग']=='अर्थ सबन्धी '].sample(2863,replace=True)
df_5 = df_5.reset_index(drop=True)
df_5.shape

(2863, 3)

In [16]:
df_6=df[df['गुनासो वर्ग']=='खानेपानी सम्बन्धी '].sample(2863,replace=True)
df_6 = df_6.reset_index(drop=True)
df_6.shape

(2863, 3)

In [17]:
df_7=df[df['गुनासो वर्ग']=='सूचना तथा  संचार सम्बन्धी'].sample(2863,replace=True)
df_7 = df_7.reset_index(drop=True)
df_7.shape

(2863, 3)

In [18]:
df_8=df[df['गुनासो वर्ग']=='शान्ति सुरक्षा सम्बन्धी '].sample(2863,replace=True)
df_8 = df_8.reset_index(drop=True)
df_8.shape

(2863, 3)

In [19]:
df_9=df[df['गुनासो वर्ग']=='प्राकृतिक श्रोत/साधन सम्बन्धी'].sample(2863,replace=True)
df_9 =df_9.reset_index(drop=True)
df_9.shape

(2863, 3)

In [20]:
df_10=df[df['गुनासो वर्ग']=='लागु पदार्थ सम्बन्धी '].sample(2863,replace=True)
df_10 = df_10.reset_index(drop=True)
df_10.shape

(2863, 3)

In [21]:
df_11=df[df['गुनासो वर्ग']=='अर्थिक अनियमितता तथा भ्रष्टाचार सम्बन्धी '].sample(2863,replace=True)
df_11 = df_11.reset_index(drop=True)
df_11.shape

(2863, 3)

In [22]:
df_12=df[df['गुनासो वर्ग']=='सूचना तथा  संचार सम्बन्धी'].sample(2863,replace=True)
df_12 = df_12.reset_index(drop=True)
df_12.shape

(2863, 3)

In [23]:
df_final=pd.concat([df_1,df_2,df_3,df_4,df_5,df_6,df_7,df_8,df_9,df_10,df_11,df_12],axis=0)

In [24]:
df_final.shape

(34356, 3)

In [25]:
2863*12


34356

In [26]:
X=df_final['गुनासो']
y=df_final['गुनासो वर्ग no']

In [27]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [29]:
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report

In [30]:
clf=Pipeline([
    ('vectorizer_tfidf',TfidfVectorizer()),
    ('random_forest',RandomForestClassifier())
])
clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00       554
           1       1.00      1.00      1.00       587
           2       1.00      1.00      1.00       596
           3       0.89      0.91      0.90       591
           4       0.96      0.95      0.96       569
           5       0.84      0.75      0.79       564
           7       0.98      1.00      0.99      1109
           8       0.95      0.97      0.96       543
           9       0.83      0.83      0.83       568
          10       1.00      0.98      0.99       598
          11       0.95      0.99      0.97       593

    accuracy                           0.95      6872
   macro avg       0.94      0.94      0.94      6872
weighted avg       0.95      0.95      0.95      6872



In [31]:
y_test[:5]


2542    10
2390     3
2809     7
926     11
940     11
Name: गुनासो वर्ग no, dtype: int64

In [32]:
y_pred[:5]

array([10,  3,  7, 11, 11])

In [33]:
test_text='बिगत ६ महिना देखि UAE मा अलपत्र परेका शिव बच्चन रौनियार, विदेश पठाउनलाई मेन पावरले २ लाख रुपैया लिएको, कम्पनीमा गएर २ घण्टा मात्र काम गर्न लगाएर काम बांट निकालदिएको। बारमबार BBC र News channel बांट उदार गर्ने भनि डकुमेन्टरी आएर पनि, UAE स्थित नेपाली एम्बेसीले जिम्मा लिएर पनि, दुई दुई पटक एयरपोर्ट बांट फिर्ता जानु परेर हाल सम्म‌ उदार हुन नसकेको अवस्था छ, वहाको परिवारमा धेरै दयनिय अवस्था छ। याहाहरु बांट अंन्तिम आशा छ कि वहाको उदार होस । हजुरहरुको जवाफको प्रतिक्षामा । धन्यवाद। पिडितको नाम :शिव बच्चन रौनियार ठेगाना :कलैया उपमहानगरपालिका-९,बारा हाल : यु ए ई मा ६ महिना देखि अलपत्र ह्वाटस्प न: 9865333333'

In [34]:
pred=clf.predict([test_text])

In [35]:
pred

array([5])

In [36]:
from gensim.models import Word2Vec

In [37]:
model = Word2Vec(sentences=df['गुनासो'], vector_size=100, window=5, min_count=1, workers=4)

In [38]:
def text_to_vector(text):
    vector = np.zeros(model.vector_size)
    count = 0
    for word in text:
        if word in model.wv:
            vector += model.wv[word]
            count += 1
    if count != 0:
        vector /= count
    return vector


In [39]:
text_to_vector(df['गुनासो'][3])

array([-0.45174699,  0.03092936,  0.15116063,  0.34442481, -0.01424103,
        0.04766228,  0.0663394 ,  0.16198674, -0.4530708 , -0.42742902,
        0.18304808, -0.17488931, -0.12907284,  0.10301939,  0.02161303,
        0.43539804,  0.48203855,  0.25957606, -0.10646672, -0.18419296,
       -0.16323378,  0.08559945,  0.31866736,  0.08813356,  0.40474231,
        0.44266875,  0.24217436,  0.00796378, -0.07483709,  0.18994797,
       -0.18462641,  0.21231188, -0.02373478,  0.11072595, -0.19557682,
        0.02455834,  0.43303517, -0.25636889,  0.31243941,  0.6201887 ,
        0.32294287,  0.2024299 , -0.28878903, -0.13582053, -0.10402035,
        0.37877804,  0.0314747 ,  0.12442988, -0.26252799, -0.40974101,
       -0.07477982,  0.33378025, -0.16170068,  0.53405573, -0.02723502,
       -0.47005404,  0.16511566, -0.03705193,  0.51485708,  0.32086139,
        0.10528897,  0.15727918, -0.15679612, -0.11294041,  0.18103292,
       -0.44297798,  0.097349  , -0.53470506,  0.68960636,  0.06

In [40]:
df['गुनासो vector'] = df['गुनासो'].apply(text_to_vector)


In [41]:
from sklearn.preprocessing import LabelEncoder


In [42]:
X = np.stack(df['गुनासो vector'].to_numpy())
le = LabelEncoder()
y = le.fit_transform(df['गुनासो वर्ग no']) 

In [43]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [44]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [45]:
predictions = rf_model.predict(X_test)
print(classification_report(y_test, predictions))


              precision    recall  f1-score   support

           0       1.00      0.03      0.05        36
           1       0.00      0.00      0.00        47
           2       0.00      0.00      0.00        14
           3       0.37      0.45      0.41       293
           4       0.38      0.11      0.17       158
           5       0.28      0.34      0.31       377
           7       0.41      0.16      0.23       139
           8       0.23      0.04      0.06       189
           9       0.43      0.79      0.55       528
          10       0.62      0.15      0.25       130
          11       0.53      0.39      0.45       156

    accuracy                           0.39      2067
   macro avg       0.39      0.22      0.23      2067
weighted avg       0.39      0.39      0.34      2067



/home/nadika/Documents/Major/major_dataset_basanta_sir/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/nadika/Documents/Major/major_dataset_basanta_sir/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/nadika/Documents/Major/major_dataset_basanta_sir/venv/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` paramete

In [46]:
from gensim.models import Word2Vec


In [47]:
model_path = "nepaliW2V_5Million.model"  # Replace with the path to your model file
model = Word2Vec.load(model_path)

In [48]:
word_vector = model.wv['खानेपानी']
word_vector

array([-1.2064941e+00,  3.9402180e+00, -5.3299463e-01,  5.8262211e-01,
       -2.8884690e+00,  2.0310917e+00,  2.2017171e+00, -6.9092125e-01,
       -3.3459987e-02, -2.8237641e+00, -2.2161863e+00, -2.0649873e-02,
        2.3419936e+00,  2.1083393e+00, -1.6098723e+00,  1.6880232e+00,
        1.0636003e+00, -4.3425158e-01,  2.8757712e-01, -1.2578536e+00,
       -8.1826556e-01,  2.5708151e+00,  1.1200736e+00,  1.9373624e+00,
       -2.2005215e+00, -1.9701147e-01,  1.0601394e+00, -6.0928788e-02,
        3.4843716e-01,  1.2614126e+00,  1.9669743e+00,  1.6927626e+00,
       -4.0942243e-01,  1.1842006e+00, -3.7725961e+00,  5.9360400e-02,
        2.5472122e-01,  7.1956187e-01,  2.2656856e-01, -1.8729920e+00,
        5.1248568e-01,  5.5080795e+00,  4.6663639e-01,  5.4816031e-01,
        2.3054123e+00,  2.4201939e-01,  5.7599324e-01, -6.9919479e-01,
       -2.5615044e+00,  2.4187551e-01, -5.6440693e-01, -3.8744307e-01,
        3.8822532e-01, -7.1457523e-01, -6.1328107e-01, -1.3851643e-01,
      

In [49]:
from nltk.tokenize import word_tokenize
import numpy as np
# Function to convert text to vectors
def text_to_vector(text):
    vector = np.zeros(model.vector_size)
    count = 0
    for word in word_tokenize(text):
        if word in model.wv:
            vector += model.wv[word]
            count += 1
    if count != 0:
        vector /= count
    return vector

In [57]:
df_final['गुनासो vector'] = df_final['गुनासो'].apply(text_to_vector)


In [58]:
df_final.sample(1)

गुनासो वर्ग  \
1841  प्राकृतिक श्रोत/साधन सम्बन्धी   

                                                                                                                                                                                                                                                                                                                                                                                                  गुनासो  \
1841  पोखरा महतगौडा साबिक छिनेडाडा कित्ता पाटन क्षेत्रमा सार्बजनिक पुरानो पोखरीलाई पुरी ब्यक्तिगत प्रयोजन जग्गाको मोहोडा पार्न बाटो निर्माण गरिएको हुदा त्यस सार्बजनिक सम्पत्ति एबम पुरानो पोखरी गाईबस्तु चराचुरुङ्गी खडेरीमा पानी खाने समेतलाई प्रयोग भबिस्यमा पोखरीको ठुलो महत्व रहने भयकाले उक्त बाटो हटाई पोखरीलाई संरक्षण प्राकृतिक स्रोत साधनलाई बचाउ गरिदिनु सम्बन्धित निकायलाई ध्यानाकर्षण गराउन   

      गुनासो वर्ग no  \
1841               1   

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   गुनासो vector  
1841  [-0.3138177788350731, 0.10243723989050421, -0.3794575213558144, 0.12733528587139314, 0.5553500348598592, 0.15180593159877592, 0.5512531042800725, -0.11522541096847919, 0.10982962679635319, -1.0965657931390322, -0.30346539422559243, 0.19046474235235816, 0.09776020091440943, 0.23814971258656847, -0.22579020460964078, -0.2519104014564719, 0.32738777219007414, 0.11148512897650814, -0.0035014599561691284, 0.37920010329172427, -0.09343252085252768, 0.4951999944427775, 0.9756935856356803, -0.08998185647134152, 0.05344808963127434, 0.24470383920318758, 0.057581965940900974, 0.17768002156582144, 0.2950783917783863, -0.3274682371928874, 0.12921667696597675, 0.12627491949953967, 0.17315242660212485, -0.24484376342863673, -0.11853432282158691, -0.21019269209096414, 0.572930367766983, -0.1732957483165794, 0.06765381455706018, -0.44096428740562665, 0.07930670418621351, 0.18009955146246487, 0.9642225963373979, 0.2388678206027382, 0.12528133692426813, 0.05195976511883297, 0.060360900

In [59]:
le = LabelEncoder()
y = le.fit_transform(df_final['गुनासो वर्ग no'])


In [60]:
X = np.vstack(df_final['गुनासो vector'])


In [54]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [61]:
# Initialize and train a Random Forest model
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [62]:
predictions = rf_model.predict(X_test)
print(classification_report(y_test, predictions))

              precision    recall  f1-score   support

           0       1.00      0.25      0.40        36
           1       0.83      0.53      0.65        47
           2       0.00      0.00      0.00        14
           3       0.54      0.60      0.57       293
           4       0.53      0.41      0.46       158
           5       0.37      0.39      0.38       377
           7       0.73      0.39      0.51       139
           8       0.57      0.39      0.46       189
           9       0.48      0.77      0.59       528
          10       0.72      0.16      0.26       130
          11       0.86      0.59      0.70       156

    accuracy                           0.52      2067
   macro avg       0.60      0.41      0.45      2067
weighted avg       0.56      0.52      0.50      2067

